const CACHE='fieldverify-pro-v102542-stable-single-load';
const REQUIRED_BUILD='10.25.42';
const CORE=['./','./index.html','./version-lock-v1024.js','./drawing-manager-waler-patch-v102537.js','./waler-mode-v102536.js','./drawing-markup-v102539.js','./import-button-label-v102540.js','./ers-touch-magnifier-v102516.js','./item-type-label-fix-v102532.js','./cloud-sync-v1024.js','./cloud-photo-accelerator-v1024.js','./hosted-backup-v1024.js','./backup-choice-v1024.js','./cloud-photo-upload-fix-v102518.js','./photo-link-display-fix-v102521.js','./photo-viewer-v1027.js','./drawing-manager-v1024.js','./drawing-delete-page-v1024.js','./caisson-final-workbook-import-v10253.js','./poured-status-v10254.js','./inspection-status-fix-v10257.js','./xlsx.full.min.js','./caisson-plan.png','./caisson-data.js','./pdf-lib.min.js','./manifest.webmanifest'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.allSettled(CORE.map(async url=>{try{const r=await fetch(new Request(url,{cache:'reload'}));if(r&&r.ok)await cache.put(url,r.clone())}catch{}}));await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
function inject(html,tag){const at=html.toLowerCase().lastIndexOf('</body>');return at>=0?html.slice(0,at)+tag+html.slice(at):html+tag}
async function patchHtml(response){let html=await response.text();
  html=html.replace(/v(?:7|10)\.\d+(?:\.\d+)?\s+stable/gi,'v10.25.42 stable');
  html=html.replace(/<script[^>]+ers-readable-numbers-v102512\.js[^>]*><\/script>/gi,'');
  html=html.replace(/service-worker\.js\?v=(?:7|10)\.\d+(?:\.\d+)?/gi,'sw.js?v=10.25.42');
  html=html.replace(/\?v=(?:7|10)\.\d+(?:\.\d+)?/gi,'?v=10.25.42');
  const files=['drawing-manager-v1024.js','drawing-manager-waler-patch-v102537.js','waler-mode-v102536.js','drawing-markup-v102539.js','import-button-label-v102540.js','cloud-sync-v1024.js','cloud-photo-accelerator-v1024.js','hosted-backup-v1024.js','backup-choice-v1024.js','cloud-photo-upload-fix-v102518.js','photo-link-display-fix-v102521.js','photo-viewer-v1027.js','ers-touch-magnifier-v102516.js','item-type-label-fix-v102532.js','caisson-final-workbook-import-v10253.js','poured-status-v10254.js','inspection-status-fix-v10257.js','version-lock-v1024.js'];
  for(const file of files){const re=new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\?v[^"\\\'<> ]*)?','g');if(html.includes(file))html=html.replace(re,file+'?v=10.25.42');else html=inject(html,`<script src="./${file}?v=10.25.42"></script>`)}
  return new Response(html,{status:response.status,statusText:response.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate'}})
}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;if(event.request.mode==='navigate'){event.respondWith((async()=>{try{const r=await fetch(event.request,{cache:'no-store'});const p=await patchHtml(r);const c=await caches.open(CACHE);await c.put('./index.html',p.clone());await c.put('./',p.clone());return p}catch{const cached=await caches.match('./index.html',{cacheName:CACHE})||await caches.match('./',{cacheName:CACHE});return cached?patchHtml(cached):new Response('FieldVerify Pro is offline.',{status:503})}})());return}if(/\/(version-lock-v1024|drawing-manager-waler-patch-v102537|waler-mode-v102536|drawing-markup-v102539|import-button-label-v102540|ers-touch-magnifier-v102516|item-type-label-fix-v102532|cloud-sync-v1024|cloud-photo-accelerator-v1024|cloud-photo-upload-fix-v102518|photo-link-display-fix-v102521|photo-viewer-v1027|hosted-backup-v1024|backup-choice-v1024|drawing-manager-v1024|drawing-delete-page-v1024|caisson-final-workbook-import-v10253|poured-status-v10254|inspection-status-fix-v10257)\.js$/.test(url.pathname)){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async r=>{if(r&&r.ok){const c=await caches.open(CACHE);await c.put('./'+url.pathname.split('/').pop(),r.clone())}return r}).catch(()=>caches.match('./'+url.pathname.split('/').pop(),{cacheName:CACHE})));return}event.respondWith(caches.match(event.request,{cacheName:CACHE}).then(cached=>cached||fetch(event.request).then(async r=>{if(r&&r.ok){const c=await caches.open(CACHE);await c.put(event.request,r.clone())}return r})))});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting()});