const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const {webcrypto}=require('node:crypto');
const root=path.resolve(__dirname,'..');
function fixture(){
 const stores={photos:new Map(),settings:new Map(),ncrPdfs:new Map()},nodes=new Map(),messages=[],downloads=[];
 let failPhoto=false,failLocal=false;
 const local=new Map();
 const localStorage={getItem:k=>local.get(k)||null,setItem(k,v){if(failLocal)throw Error('QuotaExceeded');local.set(k,String(v))},removeItem:k=>local.delete(k),key:i=>[...local.keys()][i],get length(){return local.size}};
 const node=id=>{if(!nodes.has(id))nodes.set(id,{id,style:{},classList:{add(){},remove(){}},appendChild(){},querySelector:s=>node(s.replace(/^#/,'')),querySelectorAll:()=>[],remove(){},setAttribute(){},insertAdjacentElement(){},textContent:'',innerHTML:''});return nodes.get(id)};
 const openDB=async()=>({close(){},transaction(names,mode){const tx={};const pending=[];let timer;const finish=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(pending.length)return finish();if(failPhoto&&mode==='readwrite'&&(Array.isArray(names)?names:[names]).includes('photos')){tx.error=Error('Storage failure');tx.onabort?.();return}for(const op of tx.writes||[])op();tx.oncomplete?.()},0)};
 tx.objectStore=name=>({get(id){const req={};pending.push(req);setTimeout(()=>{req.result=stores[name].get(id);req.onsuccess?.();pending.splice(pending.indexOf(req),1);finish()},0);return req},getAll(){const req={};pending.push(req);setTimeout(()=>{req.result=[...stores[name].values()];req.onsuccess?.();pending.splice(pending.indexOf(req),1);finish()},0);return req},getAllKeys(){const req={};pending.push(req);setTimeout(()=>{req.result=[...stores[name].keys()];req.onsuccess?.();pending.splice(pending.indexOf(req),1);finish()},0);return req},put(row){(tx.writes??=[]).push(()=>stores[name].set(row.id,row));finish();return{}},delete(id){(tx.writes??=[]).push(()=>stores[name].delete(id));finish()}});finish();return tx}});
 const context={console,Blob,File,TextEncoder,TextDecoder,URL,crypto:webcrypto,Map,Set,Promise,Date,Error,Uint8Array,JSON,atob,btoa,localStorage,navigator:{onLine:true},document:{readyState:'loading',hidden:false,getElementById:node,createElement:()=>node('new'),body:{appendChild(){}},addEventListener(){},querySelector:()=>null},addEventListener(){},setInterval(){},setTimeout:(fn,ms)=>ms>50?0:setTimeout(fn,ms),clearTimeout,openDB,activeProjectId:'local',projects:[{id:'local',cloudId:'706d927d-a8a1-4589-97be-7581a4fa006e',name:'Test'}],records:{},ncrRows:[],activeProject(){return context.projects.find(p=>p.id===context.activeProjectId)},projectRecordsKey:(id=context.activeProjectId)=>'fieldVerifyProjectRecords:'+id,projectNcrKey:()=> 'ncr',drawingStorageId:()=> 'drawing:local',defaultRec:()=>({photos:[]}),persist(){localStorage.setItem(context.projectRecordsKey(),JSON.stringify(context.records))},persistNcr(){},renderPins(){},showTarget(){},fitTransform(){},showProjectHome(){},applyStoredDrawing:async()=>{},saveProjects(){},loadRecords(){},toast:s=>messages.push(s),downloadFile:f=>downloads.push(f),savePhotos:async()=>{},NEW_KEY:'foundationInspectorRecords',NCR_KEY:'ncr',persistNcr(){},blobToDataURL:async b=>'data:'+b.type+';base64,'+Buffer.from(await b.arrayBuffer()).toString('base64'),dataURLToBlob:s=>new Blob([Buffer.from(s.split(',')[1],'base64')],{type:s.slice(5,s.indexOf(';'))}),allFromStore:async(db,n)=>[...stores[n].values()]};context.window=context;vm.createContext(context);
 return{context,stores,node,messages,downloads,setFailPhoto:v=>failPhoto=v,setFailLocal:v=>failLocal=v,run(file){vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context)}};
}
function cloudFixture(){const f=fixture(),c=f.context;const remote={fieldverify_projects:[c.projects[0]],fieldverify_records:[],fieldverify_project_state:[],fieldverify_photos:[]},files=new Map(),uploads=[],downloaded=[];let failing=new Set(),switchOnDownload=false;
 const client={auth:{getSession:async()=>({data:{session:{user:{email:'test'}}}}),onAuthStateChange(){}},channel:()=>({on(){return this},subscribe(){return this}}),removeChannel:async()=>{},from(table){let filters=[],range=null,method='select',value;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},range(a,b){range=[a,b];return q},maybeSingle(){q.isSingle=true;return q},single(){q.isSingle=true;return q},upsert(v){method='upsert';value=v;return q},then(resolve,reject){return Promise.resolve().then(()=>{let rows=remote[table]||[];if(method==='upsert'){for(const r of Array.isArray(value)?value:[value]){const i=rows.findIndex(x=>table==='fieldverify_photos'?x.id===r.id:x.item_key===r.item_key&&x.project_id===r.project_id);if(i<0)rows.push(r);else rows[i]=r}return{data:value,error:null}}rows=rows.filter(r=>filters.every(([k,v])=>r[k]===v));if(range)rows=rows.slice(range[0],range[1]+1);return{data:q.isSingle?rows[0]||null:rows,error:null}}).then(resolve,reject)}};return q},storage:{from(){return{upload:async(p,b)=>{uploads.push(p);if(failing.has(p))return{error:{message:'Network failed'}};files.set(p,b);return{error:null}},download:async p=>{downloaded.push(p);if(switchOnDownload)c.activeProjectId='other';return{data:files.get(p),error:files.has(p)?null:{message:'Not found'}}}}}}};c.mockClient=client;
 let source=fs.readFileSync(path.join(root,'cloud-sync-v1024.js'),'utf8');source=source.replace(/const mod=await import\([^;]+;sb=mod.createClient\([^;]+;/,'sb=mockClient;');vm.runInContext(source,c);
 return{...f,remote,files,uploads,downloaded,fail:paths=>failing=new Set(paths),switchOnDownload:()=>switchOnDownload=true};
}
test('each capture commits its file and recovery link; failed transactions report failure',async()=>{const f=fixture(),c=f.context;const html=fs.readFileSync(path.join(root,'index.html'),'utf8');vm.runInContext(html.slice(html.indexOf('let photoSaveQueue'),html.indexOf('async function showPhotoPreview')),c);await c.savePhotos(309,[new File(['photo'],'a.jpg',{type:'image/jpeg'})]);assert.equal(f.stores.photos.size,1);assert.equal(c.records[309].photos.length,1);assert.equal(f.stores.settings.size,0);f.setFailPhoto(true);await assert.rejects(c.savePhotos(310,[new File(['failed'],'b.jpg')]),/Storage failure/);assert.equal(c.records[310],undefined);assert.equal(f.stores.photos.size,1)});
test('a localStorage failure leaves a committed photo link that is recovered after reload',async()=>{const f=fixture(),c=f.context;const html=fs.readFileSync(path.join(root,'index.html'),'utf8');vm.runInContext(html.slice(html.indexOf('let photoSaveQueue'),html.indexOf('async function showPhotoPreview')),c);f.setFailLocal(true);await assert.rejects(c.savePhotos(329,[new File(['safe'],'a.jpg')]),/QuotaExceeded/);assert.equal(f.stores.photos.size,1);assert.equal(f.stores.settings.size,1);f.setFailLocal(false);c.records={};await c.recoverPendingPhotoLinks();assert.equal(c.records[329].photos.length,1);assert.equal(f.stores.settings.size,0)});
test('uploads drain all 270 linked photos, without the old 2/5 photo cap',async()=>{const f=cloudFixture(),c=f.context;for(let i=0;i<270;i++){f.stores.photos.set('p'+i,{id:'p'+i,caisson:309,blob:new Blob(['p'])});c.records[309]??={photos:[]};c.records[309].photos.push('p'+i)}await c.FIELDVERIFY_CLOUD_SYNC.init();const result=await c.FIELDVERIFY_CLOUD_SYNC.uploadPhotos();assert.equal(result.uploaded,270);assert.equal(result.failed.length,0);assert.equal(f.uploads.length,270);const again=await c.FIELDVERIFY_CLOUD_SYNC.uploadPhotos();assert.equal(again.uploaded,0)});
test('failed uploads and missing local files are counted; retry resumes only pending files',async()=>{const f=cloudFixture(),c=f.context;c.records[309]={photos:['ok','bad','missing']};for(const id of ['ok','bad'])f.stores.photos.set(id,{id,caisson:309,blob:new Blob([id])});await c.FIELDVERIFY_CLOUD_SYNC.init();const bad=c.projects[0].cloudId+'/309/bad.jpg';f.fail([bad]);const r=await c.FIELDVERIFY_CLOUD_SYNC.uploadPhotos();assert.equal(r.uploaded,1);assert.equal(r.failed.length,1);assert.equal(r.missing,1);f.fail([]);const retry=await c.FIELDVERIFY_CLOUD_SYNC.uploadPhotos();assert.equal(retry.uploaded,1);assert.equal(retry.failed.length,0)});
test('cloud download paginates, stores actual blobs, and resumes without re-downloading',async()=>{const f=cloudFixture(),c=f.context;for(let i=0;i<211;i++){f.remote.fieldverify_photos.push({id:'r'+i,project_id:c.projects[0].cloudId,item_key:'309',storage_path:'remote/'+i});f.files.set('remote/'+i,new Blob(['original '+i]))}await c.FIELDVERIFY_CLOUD_SYNC.init();const r=await c.FIELDVERIFY_CLOUD_SYNC.downloadPhotos();assert.equal(r.saved,211);assert.equal(f.stores.photos.size,211);const again=await c.FIELDVERIFY_CLOUD_SYNC.downloadPhotos();assert.equal(again.cached,211);assert.equal(f.downloaded.length,211)});
test('project switch during download cannot put the photo into the new project',async()=>{const f=cloudFixture(),c=f.context;f.remote.fieldverify_photos.push({id:'x',project_id:c.projects[0].cloudId,item_key:'309',storage_path:'x'});f.files.set('x',new Blob(['photo']));await c.FIELDVERIFY_CLOUD_SYNC.init();f.switchOnDownload();const r=await c.FIELDVERIFY_CLOUD_SYNC.downloadPhotos();assert.equal(r.failed.length,1);assert.equal(f.stores.photos.size,0)});
test('device parts round-trip original photo bytes and NCR/drawing attachments',async()=>{const f=fixture(),c=f.context;c.records[309]={photos:['a','b'],notes:'keep',updated:'2026-09-29'};f.stores.photos.set('a',{id:'a',caisson:309,blob:new Blob([new Uint8Array(5*1024*1024).fill(65)],{type:'image/jpeg'})});f.stores.photos.set('b',{id:'b',caisson:309,blob:new Blob([new Uint8Array(5*1024*1024).fill(66)],{type:'image/jpeg'})});f.stores.ncrPdfs.set('NCR1',{id:'NCR1',blob:new Blob(['pdf'],{type:'application/pdf'})});f.stores.settings.set('drawing:local',{id:'drawing:local',blob:new Blob(['drawing'])});f.run('device-backup-v102590.js');await c.FIELDVERIFY_DEVICE_BACKUP.prepare();await f.node('fvPartsSave').onclick();await f.node('fvPartsNext').onclick();await f.node('fvPartsSave').onclick();assert.equal(f.downloads.length,2);assert.ok(f.downloads.every(x=>x.size<8*1024*1024));c.records={};f.stores.photos.clear();f.stores.settings.clear();f.stores.ncrPdfs.clear();await c.FIELDVERIFY_DEVICE_BACKUP.restoreParts(f.downloads);assert.equal(c.records[309].notes,'keep');assert.equal(f.stores.photos.size,2);assert.equal((new Uint8Array(await f.stores.photos.get('a').blob.arrayBuffer()))[0],65);assert.equal((new Uint8Array(await f.stores.photos.get('b').blob.arrayBuffer()))[0],66);assert.equal(await f.stores.ncrPdfs.get('NCR1').blob.text(),'pdf');assert.equal(await f.stores.settings.get('drawing:local').blob.text(),'drawing')});
test('viewer only returns exact linked IDs and cannot pick an unrelated same-number photo',async()=>{const f=fixture(),c=f.context;c.records[309]={photos:['mine']};f.stores.photos.set('mine',{id:'mine',caisson:309,blob:new Blob(['mine'])});f.stores.photos.set('other',{id:'other',caisson:309,projectId:'other',blob:new Blob(['other'])});f.run('photo-link-display-fix-v102521.js');const photos=await c.getPhotos(309);assert.equal(photos.length,1);assert.equal(photos[0].id,'mine');assert.equal((await c.getPhotos(310)).length,0)});
